### ISSUE TITLE
alt0-mtalk.google.com等记录导致gcm无法正常使用

### ISSUE THREAD

**Issue by Hubedge** [lack006/Android-Hosts-L#7]
`alt0-mtalk.google.com`至`alt9-mtalk.google.com`被指向SNI服务器`219.76.4.4`的hosts记录导致gcm无法正常连接，大概是因为gcm使用了SNI不支持的协议。

此外，国内各主流DNS（测试了114、DNSPod、百度、阿里）解析这些域名得出的IP（一般以`.188`结尾，如`74.125.192.188` `173.194.210.188` `64.233.186.188`）未被屏蔽，且能顺利使用gcm服务，因此建议从hosts中删除这些域名，或将其指向正确的解析结果。

**Comment by Hubedge** [comment]
补充一点信息：

不存在`alt0-mtalk.google.com`和`alt9-mtalk.google.com`这两台服务器，只有1到8。

`alt*-mtalk.google.com`是在`mtalk.google.com`连不通时的备用服务器。`mtalk.google.com`指向`219.76.4.*`时，gcm走`alt*-mtalk.google.com`，可见`mtalk.google.com`也不应指向`219.76.4.*`。

同区域的以下域名可能也不应指向SNI：
> gcm.googleapis.com
gcm.l.google.com
gcm-xmpp.googleapis.com
gcm-preprod.l.google.com
gcm-preprod.googleapis.com

**Comment by lack006** [comment]
谢谢，我找个时间测试一下。

**Comment by Hubedge** [comment]
现在好了，感谢
